### PR TITLE
Add script for rebuilding all project builds

### LINKED ISSUE #17: Fix readme script instructions
`follow_repos_by_search_term_via_code_instances.py` is named in the readme however it's been deleted and renamed to `follow_repos_by_search_term.py`. We need to update the readme to reflect that.

### LINKED ISSUE #18: Add script to re-run projects that failed a build
I recently added a bunch of projects to LGTM.com but almost 1/3 (around 800 projects) failed their initial builds. Re-running those builds on those projects manually succeeded. It would be nice if there is a script that can iterate through all failed project builds and automatically re-run them.

### PR DESCRIPTION
**Pull request by mrthankyou**
Resolves #17 and #18.

Tested locally and everything seems to work just fine. All projects that failed in my LGTM.account was restarted.

### CODE REVIEW

**Review by JLLeitschuh — APPROVED** [review]
LGTM!

**Comment by mrthankyou** [comment]
Do not merge this script yet. I realized there is no rate throttling and would like to add it to prevent any rate limit issues on LGTM's end.

**Comment by mrthankyou** [comment]
Tested and confirmed throttling works.

**Review by JLLeitschuh — APPROVED** [review]
LGTM!

**Pull request merged**
